# SPDX-FileCopyrightText: 2020 Luke Granger-Brown
#
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.3
    hooks:
    -   id: isort
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.11.1
    hooks:
    -   id: reuse